# Generated by Django 4.2.1 on 2023-05-27 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPP', '0004_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyAPP.proyecto'),
            preserve_default=False,
        ),
    ]
