# Generated by Django 4.2.1 on 2023-05-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPP', '0005_articulo_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goleadores',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='Estadios',
        ),
        migrations.DeleteModel(
            name='Goleadores',
        ),
        migrations.DeleteModel(
            name='Puntuacion',
        ),
    ]
